### ISSUE TITLE
__init__() missing 1 required positional argument: 'param'

### ISSUE THREAD

**Issue by Localbug** [neo4j-partners/neo4j-generative-ai-azure#1]
Thanks for this great example. Unfortunately I'm having trouble getting this to work.

In Step: "Let's run our completion task with our LLM" i get the error: 
__init__() missing 1 required positional argument: 'param'

Do you have any idea how to fix it?

![NotebookError](https://github.com/neo4j-partners/neo4j-generative-ai-azure/assets/44060386/74e58182-4299-42ca-9dd3-60fb7c39630b)

**Comment by ezhilvendhan** [comment]
@Localbug Sorry, I couldn't replicate it. Using "openai==0.27.8". What is your version?

**Comment by Localbug** [comment]
@ezhilvendhan thank you for your quick response.
I think it has to do with the setting for OpenAI. Can you check in my screenshot below, if the values were entered correctly in the "config.env" file? I previously registered AzureOpenAI and deployed a model "GPT-35-turbo". Are there any additional steps required within AzureOpenAI?

![image](https://github.com/neo4j-partners/neo4j-generative-ai-azure/assets/44060386/307720a1-36fa-40fa-859b-1b3eccc0fb58)

![image](https://github.com/neo4j-partners/neo4j-generative-ai-azure/assets/44060386/7eec2bbd-aac1-47ac-971a-43907f89851b)

Thank you

**Comment by ezhilvendhan** [comment]
Looks like OPENAI_API_VERSION is missing in your env file. You can you provide it from the Model deployments page in Azure console

**Comment by Jayesh-upvision** [comment]
Hello Guys

I have this config in my config.env

```
OPENAI_API_TYPE = "azure"
OPENAI_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
OPENAI_API_BASE=https://ml-test-1.openai.azure.com
OPENAI_API_VERSION=2023-05-15
OPENAI_MODEL_NAME = "gpt-4-32k"
OPENAI_DEPLOYMENT_NAME = "deployment-ml"
NEO4J_CONN_URL=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=abc@123
``` 

and it is working for me.
