### ISSUE TITLE
Streamlit application external url is not accessible

### ISSUE THREAD

**Issue by Jayesh-upvision** [neo4j-partners/neo4j-generative-ai-azure#2]
Hello team,

I have created Azure machine learning model and dumped data to neo4j database in azure portal ml.azure.com compute instance.
however when I run the below command from the location ~/cloudfiles/code/Users/sumeet/neo4j-generative-ai-azure/ui/streamlit

`streamlit run Home.py`

It showed me this output

```
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  Network URL: http://10.0.0.5:8501
  External URL: http://20.75.107.185:8501
``` 

But when I open http://20.75.107.185:8501 in my browser is not working.

Does anybody have any idea?

Thanks

**Comment by Jayesh-upvision** [comment]
@ezhilvendhan
Can you please help here ?

**Comment by ezhilvendhan** [comment]
@Jayesh-upvision You have to open the relevant port in the firewall. If you use Azure or some other cloud providers, you can refer to their documentation on how to open it liker [here](https://stackoverflow.com/questions/21083782/windows-azure-virtual-machine-opening-a-port)

**Comment by Jayesh-upvision** [comment]
@ezhilvendhan
Thanks
The link you have provided is for Windows VM, But the cloud instance used in the notebook in ml.azure.com is Ubuntu.
